language: ruby
rvm:
  - 1.9.3
env:
  - RAILS_VERSION='->3.2.12'
  - DB=sqlite
script:
  - bundle update && bundle install
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/
  # - bundle exec rake tests
branches:
  only:
    - master 
